<a href="https://colab.research.google.com/github/singh-priyanshi/TECH-2335/blob/main/3_3_Groceries_Exercise_(Summer_2023).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

version: 2023-07-14 (adds unit tests to setup section)

## References

  + [Lists](https://github.com/prof-rossetti/intro-to-python/blob/master/notes/python/datatypes/lists.md)
  + [Dictionaries](https://github.com/prof-rossetti/intro-to-python/blob/master/notes/python/datatypes/dictionaries.md)
  + [List Comprehensions](https://docs.python.org/3/tutorial/datastructures.html?#list-comprehensions)

# Instructions

Make a copy of this notebook so you can edit and save your own version of it. Do the work in your copy of the notebook.

The setup cell provides a Python variable called `products` and a function called `to_usd`. Remember to run the setup cells before proceeding to development.

Write Python code in the cells below to transform the provided `products` variable into the desired information outputs.

# Collaboration

It is OK to discuss this exercise generally with other students, to work together, and even to share some small code snippets!

NOTE: if you receive any help from another student, you are expected to provide appropriate attribution in a corresponding text cell or code comment, like "Student X helped me with this part", or "Student Y and I worked on this part together".

# Evaluation

Exercise submissions will be evaluated according to the rubric below:

Question | Weight
-- | --
Part I | 50%
Part II | 50%


This rubric is tentative, and may be subject to slight adjustments during the grading process.


# Setup

In [ ]:
#
# SETUP CELL (run and leave as-is)
#

def to_usd(my_price):
    """
    Converts a numeric value to usd-formatted string, for printing and display purposes.

    Param: my_price (int or float) like 4000.444444

    Example: to_usd(4000.444444)

    Returns: $4,000.44
    """
    return f"${my_price:,.2f}" #> $12,000.71


assert to_usd(3.5) == "$3.50"
assert to_usd(4.44444) == "$4.44"
assert to_usd(1234567890) == "$1,234,567,890.00"

print(to_usd(12345.6789))

$12,345.68


In [22]:



#
# SETUP CELL (run and leave as-is)
#

products = [
    {"id":1, "name": "Chocolate Sandwich Cookies", "department": "snacks", "aisle": "cookies cakes", "price": 3.50},
    {"id":2, "name": "All-Seasons Salt", "department": "pantry", "aisle": "spices seasonings", "price": 4.99},
    {"id":3, "name": "Robust Golden Unsweetened Oolong Tea", "department": "beverages", "aisle": "tea", "price": 2.49},
    {"id":4, "name": "Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce", "department": "frozen", "aisle": "frozen meals", "price": 6.99},
    {"id":5, "name": "Green Chile Anytime Sauce", "department": "pantry", "aisle": "marinades meat preparation", "price": 7.99},
    {"id":6, "name": "Dry Nose Oil", "department": "personal care", "aisle": "cold flu allergy", "price": 21.99},
    {"id":7, "name": "Pure Coconut Water With Orange", "department": "beverages", "aisle": "juice nectars", "price": 3.50},
    {"id":8, "name": "Cut Russet Potatoes Steam N' Mash", "department": "frozen", "aisle": "frozen produce", "price": 4.25},
    {"id":9, "name": "Light Strawberry Blueberry Yogurt", "department": "dairy eggs", "aisle": "yogurt", "price": 6.50},
    {"id":10, "name": "Sparkling Orange Juice & Prickly Pear Beverage", "department": "beverages", "aisle": "water seltzer sparkling water", "price": 2.99},
    {"id":11, "name": "Peach Mango Juice", "department": "beverages", "aisle": "refrigerated", "price": 1.99},
    {"id":12, "name": "Chocolate Fudge Layer Cake", "department": "frozen", "aisle": "frozen dessert", "price": 18.50},
    {"id":13, "name": "Saline Nasal Mist", "department": "personal care", "aisle": "cold flu allergy", "price": 16.00},
    {"id":14, "name": "Fresh Scent Dishwasher Cleaner", "department": "household", "aisle": "dish detergents", "price": 4.99},
    {"id":15, "name": "Overnight Diapers Size 6", "department": "babies", "aisle": "diapers wipes", "price": 25.50},
    {"id":16, "name": "Mint Chocolate Flavored Syrup", "department": "snacks", "aisle": "ice cream toppings", "price": 4.50},
    {"id":17, "name": "Rendered Duck Fat", "department": "meat seafood", "aisle": "poultry counter", "price": 9.99},
    {"id":18, "name": "Pizza for One Suprema Frozen Pizza", "department": "frozen", "aisle": "frozen pizza", "price": 12.50},
    {"id":19, "name": "Gluten Free Quinoa Three Cheese & Mushroom Blend", "department": "dry goods pasta", "aisle": "grains rice dried goods", "price": 3.99},
    {"id":20, "name": "Pomegranate Cranberry & Aloe Vera Enrich Drink", "department": "beverages", "aisle": "juice nectars", "price": 4.25}
] # based on data from Instacart: https://www.instacart.com/datasets/grocery-shopping-2017


In [ ]:
# testing the setup process:
print(products)
print(to_usd(12345.6789))

[{'id': 1, 'name': 'Chocolate Sandwich Cookies', 'department': 'snacks', 'aisle': 'cookies cakes', 'price': 3.5}, {'id': 2, 'name': 'All-Seasons Salt', 'department': 'pantry', 'aisle': 'spices seasonings', 'price': 4.99}, {'id': 3, 'name': 'Robust Golden Unsweetened Oolong Tea', 'department': 'beverages', 'aisle': 'tea', 'price': 2.49}, {'id': 4, 'name': 'Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce', 'department': 'frozen', 'aisle': 'frozen meals', 'price': 6.99}, {'id': 5, 'name': 'Green Chile Anytime Sauce', 'department': 'pantry', 'aisle': 'marinades meat preparation', 'price': 7.99}, {'id': 6, 'name': 'Dry Nose Oil', 'department': 'personal care', 'aisle': 'cold flu allergy', 'price': 21.99}, {'id': 7, 'name': 'Pure Coconut Water With Orange', 'department': 'beverages', 'aisle': 'juice nectars', 'price': 3.5}, {'id': 8, 'name': "Cut Russet Potatoes Steam N' Mash", 'department': 'frozen', 'aisle': 'frozen produce', 'price': 4.25}, {'id': 9, 'name': 'Light Straw

# Part 1

Write python code which references the `products` variable to reproduce the following output, representing a human-friendly list of products:

```
--------------
THERE ARE 20 PRODUCTS:
--------------
 + All-Seasons Salt ($4.99)
 + Chocolate Fudge Layer Cake ($18.50)
 + Chocolate Sandwich Cookies ($3.50)
 + Cut Russet Potatoes Steam N' Mash ($4.25)
 + Dry Nose Oil ($21.99)
 + Fresh Scent Dishwasher Cleaner ($4.99)
 + Gluten Free Quinoa Three Cheese & Mushroom Blend ($3.99)
 + Green Chile Anytime Sauce ($7.99)
 + Light Strawberry Blueberry Yogurt ($6.50)
 + Mint Chocolate Flavored Syrup ($4.50)
 + Overnight Diapers Size 6 ($25.50)
 + Peach Mango Juice ($1.99)
 + Pizza For One Suprema Frozen Pizza ($12.50)
 + Pomegranate Cranberry & Aloe Vera Enrich Drink ($4.25)
 + Pure Coconut Water With Orange ($3.50)
 + Rendered Duck Fat ($9.99)
 + Robust Golden Unsweetened Oolong Tea ($2.49)
 + Saline Nasal Mist ($16.00)
 + Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce ($6.99)
 + Sparkling Orange Juice & Prickly Pear Beverage ($2.99)
 ```


In [ ]:
#
# PART 1 CODE HERE!
#

diction = '\n'.join(sorted([ f"+ {product['name']} (${product['price']})" for product in products]))

In [ ]:
print("--------------")
print("THERE ARE 20 PRODUCTS:")
print("--------------")
print(diction)

--------------
THERE ARE 20 PRODUCTS:
--------------
+ All-Seasons Salt ($4.99)
+ Chocolate Fudge Layer Cake ($18.5)
+ Chocolate Sandwich Cookies ($3.5)
+ Cut Russet Potatoes Steam N' Mash ($4.25)
+ Dry Nose Oil ($21.99)
+ Fresh Scent Dishwasher Cleaner ($4.99)
+ Gluten Free Quinoa Three Cheese & Mushroom Blend ($3.99)
+ Green Chile Anytime Sauce ($7.99)
+ Light Strawberry Blueberry Yogurt ($6.5)
+ Mint Chocolate Flavored Syrup ($4.5)
+ Overnight Diapers Size 6 ($25.5)
+ Peach Mango Juice ($1.99)
+ Pizza for One Suprema Frozen Pizza ($12.5)
+ Pomegranate Cranberry & Aloe Vera Enrich Drink ($4.25)
+ Pure Coconut Water With Orange ($3.5)
+ Rendered Duck Fat ($9.99)
+ Robust Golden Unsweetened Oolong Tea ($2.49)
+ Saline Nasal Mist ($16.0)
+ Smart Ones Classic Favorites Mini Rigatoni With Vodka Cream Sauce ($6.99)
+ Sparkling Orange Juice & Prickly Pear Beverage ($2.99)


# Part 2

Write python code which references the `products` variable to reproduce the following output, representing a human-friendly list of departments:


```
--------------
THERE ARE 10 DEPARTMENTS:
--------------
 + Babies (1 product)
 + Beverages (5 products)
 + Dairy Eggs (1 product)
 + Dry Goods Pasta (1 product)
 + Frozen (4 products)
 + Household (1 product)
 + Meat Seafood (1 product)
 + Pantry (2 products)
 + Personal Care (2 products)
 + Snacks (2 products)
 ```

In [23]:
#
# PART 2 CODE HERE!
#

from collections import Counter

departments = [product['department'] for product in products]
department_counts = Counter(departments)

print("--------------")
print("THERE ARE", len(department_counts), "DEPARTMENTS:")
print("--------------")

for department, count in department_counts.items():
    print(" +", department.capitalize(), "(", count, "product)" if count == 1 else "products", ")")





--------------
THERE ARE 10 DEPARTMENTS:
--------------
 + Snacks ( 2 products )
 + Pantry ( 2 products )
 + Beverages ( 5 products )
 + Frozen ( 4 products )
 + Personal care ( 2 products )
 + Dairy eggs ( 1 product) )
 + Household ( 1 product) )
 + Babies ( 1 product) )
 + Meat seafood ( 1 product) )
 + Dry goods pasta ( 1 product) )


In [24]:
# Get unique department names
departments = set(product["department"] for product in products)

# Create a dictionary to store the department counts
department_counts = {department: 0 for department in departments}

# Count the number of products in each department
for product in products:
    department_counts[product["department"]] += 1

# Sort the departments alphabetically
sorted_departments = sorted(department_counts.keys())

# Print the department list
print("--------------")
print("THERE ARE", len(departments), "DEPARTMENTS:")
print("--------------")
for department in sorted_departments:
    product_count = department_counts[department]
    print("+", department.capitalize(), "({} product{})".format(product_count, "s" if product_count > 1 else ""))


--------------
THERE ARE 10 DEPARTMENTS:
--------------
+ Babies (1 product)
+ Beverages (5 products)
+ Dairy eggs (1 product)
+ Dry goods pasta (1 product)
+ Frozen (4 products)
+ Household (1 product)
+ Meat seafood (1 product)
+ Pantry (2 products)
+ Personal care (2 products)
+ Snacks (2 products)


In [ ]:
dept_count = {}

for product in products:
  # print(product)
  if product['department'] in dept_count.keys():
    dept_count[product['department']] +=1

  else:
    dept_count[product['department']] = 1

In [ ]:
dept_count

{'snacks': 2,
 'pantry': 2,
 'beverages': 5,
 'frozen': 4,
 'personal care': 2,
 'dairy eggs': 1,
 'household': 1,
 'babies': 1,
 'meat seafood': 1,
 'dry goods pasta': 1}

In [ ]:
diction1 = '\n'.join(sorted([ f"+ {product['department'].title()} ({dept_count[product['department']]})" for count in dept_count]))

In [ ]:
for dept in dept_count:
  print(dept)

snacks
pantry
beverages
frozen
personal care
dairy eggs
household
babies
meat seafood
dry goods pasta


In [ ]:
diction1 = sorted([f'{key} ({value})'.title() for key, value in dept_count.items()])


In [ ]:
print("--------------")
print("THERE ARE 10 DEPARTMENTS:")
print("--------------")
print(diction1)

--------------
THERE ARE 10 DEPARTMENTS:
--------------
['Babies (1)', 'Beverages (5)', 'Dairy Eggs (1)', 'Dry Goods Pasta (1)', 'Frozen (4)', 'Household (1)', 'Meat Seafood (1)', 'Pantry (2)', 'Personal Care (2)', 'Snacks (2)']
